/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasidesain;

/**
 *
 * @author asus
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihanJurusan = new javax.swing.ButtonGroup();
        varNama = new javax.swing.JTextField();
        varAbsen = new javax.swing.JTextField();
        rdbTKJ = new javax.swing.JRadioButton();
        rdbRPL = new javax.swing.JRadioButton();
        cbPrograming = new javax.swing.JCheckBox();
        cbAnimator = new javax.swing.JCheckBox();
        cbDesainer = new javax.swing.JCheckBox();
        cbVideoEditing = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAHasil = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(varNama);
        varNama.setBounds(187, 120, 230, 30);
        getContentPane().add(varAbsen);
        varAbsen.setBounds(187, 160, 230, 30);

        pilihanJurusan.add(rdbTKJ);
        rdbTKJ.setText("TKJ");
        getContentPane().add(rdbTKJ);
        rdbTKJ.setBounds(187, 234, 43, 23);

        pilihanJurusan.add(rdbRPL);
        rdbRPL.setText("RPL");
        rdbRPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbRPLActionPerformed(evt);
            }
        });
        getContentPane().add(rdbRPL);
        rdbRPL.setBounds(322, 234, 60, 23);

        cbPrograming.setText("Programing");
        cbPrograming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProgramingActionPerformed(evt);
            }
        });
        getContentPane().add(cbPrograming);
        cbPrograming.setBounds(187, 291, 100, 23);

        cbAnimator.setText("Animator");
        getContentPane().add(cbAnimator);
        cbAnimator.setBounds(322, 291, 110, 23);

        cbDesainer.setText("Desainer");
        getContentPane().add(cbDesainer);
        cbDesainer.setBounds(187, 332, 100, 23);

        cbVideoEditing.setText("Video Editing");
        getContentPane().add(cbVideoEditing);
        cbVideoEditing.setBounds(322, 332, 110, 23);

        jLabel1.setText("BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 30, 80, 30);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 120, 50, 20);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 165, 40, 20);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hasil");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(187, 399, 52, 27);

        TAHasil.setColumns(20);
        TAHasil.setRows(5);
        jScrollPane1.setViewportView(TAHasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(142, 444, 288, 116);

        jLabel5.setText("Jurusan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(84, 240, 50, 15);

        jLabel6.setText("Hobi");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 297, 31, 15);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(86, 370, 80, 25);

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(183, 370, 80, 25);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 370, 51, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\pain.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 700, 580);

        setBounds(0, 0, 717, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbRPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbRPLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbRPLActionPerformed

    private void cbProgramingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProgramingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProgramingActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        varNama.setText("");
        varAbsen.setText("");
        cbPrograming.setSelected(false);
         cbAnimator.setSelected(false);
          cbDesainer.setSelected(false);
           cbVideoEditing.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nama = varNama.getText();
        String absen = varAbsen.getText();
        String jurusan = null;
        String hobi="";
        
        //pilihan jurusan
        if (rdbRPL.isSelected())
            jurusan="RPL";
        else if (rdbTKJ.isSelected())
            jurusan="TKJ";
        
        //pilihan hobi
        if (cbAnimator.isSelected())
           hobi+=cbAnimator.getText()+",  ";
         if (cbPrograming.isSelected())
           hobi+=cbPrograming.getText()+",  ";
          if (cbVideoEditing.isSelected())
           hobi+=cbVideoEditing.getText()+",  ";
           if (cbDesainer.isSelected())
           hobi+=cbDesainer.getText()+",";
           
           //untuk hasil
           TAHasil.setText("Nama Anda : " + nama+"\n Absen Anda : " +absen+"\nJurusan Anda : " +jurusan+"\n Hobi Anda : "+hobi);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TAHasil;
    private javax.swing.JCheckBox cbAnimator;
    private javax.swing.JCheckBox cbDesainer;
    private javax.swing.JCheckBox cbPrograming;
    private javax.swing.JCheckBox cbVideoEditing;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup pilihanJurusan;
    private javax.swing.JRadioButton rdbRPL;
    private javax.swing.JRadioButton rdbTKJ;
    private javax.swing.JTextField varAbsen;
    private javax.swing.JTextField varNama;
    // End of variables declaration//GEN-END:variables
}
